#!/usr/bin/env python3
"""Render human discovery docs from canonical registry inputs."""
import argparse
from collections import Counter
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]


def cell(value):
    if isinstance(value, list):
        value = '; '.join(value)
    return str(value).replace('|', '\\|').replace('\n', ' ')


def source_link(entry, data):
    if not entry.get('source'):
        return '[authored](../' + entry['path'] + '/SKILL.md)'
    source = data['sources'][entry['source']]
    return '[' + entry['source'] + '](https://github.com/' + source['repository'] + '/tree/' + source['commit'] + '/' + entry['path'] + ')'


def render():
    data = json.loads((ROOT / 'registry/catalog.json').read_text())
    config = json.loads((ROOT / 'registry/harness.json').read_text())
    index = json.loads((ROOT / 'registry/source-index.json').read_text())
    entries = data['skills']; by_id = {e['id']: e for e in entries}
    counts = Counter(e['scope'] for e in entries)
    count_line = ('**' + str(len(config['global_skills'])) + ' default global skills, '
                  + str(counts['project']) + ' installable project selections, '
                  + str(len(data['profiles'])) + ' profiles, ' + str(counts['manual'])
                  + ' manual integrations, and ' + format(len(index['skills']), ',')
                  + ' indexed source entries across ' + str(len(data['sources'])) + ' sources.**')
    catalog = ['# Skill catalog', '', '<!-- Generated by scripts/render_registry.py; edit registry inputs. -->', '', count_line, '',
               'Default globals are declared in [harness.json](../registry/harness.json). Some are also project-selectable; these counts overlap. `scope: global` identifies the original setup-only foundations, while the manifest is authoritative for the expanded global set.', '',
               'Use `python3 ai.py catalog show <id>` for complete coverage, dependencies, companions, adaptations and caveats. `search <query>` combines curated task tags and authored skills with the broader inventory; indexed metadata alone is not installation approval.', '',
               '## Default globals', '', '| Skill | Purpose |', '| --- | --- |']
    for identifier in config['global_skills']:
        e = by_id[identifier]
        catalog.append('| [' + identifier + '](../' + e['path'] + '/SKILL.md) | ' + cell(e['description']) + ' |')
    defaults = ', '.join('`' + name + '`' for name in config.get('project_defaults', {}).get('profiles', []))
    catalog += ['', '## Composable project profiles', '',
                'New project init and explicit project add include the configured foundation profiles: ' + (defaults or 'none') + '. Add specialists for current needs and credible later stages grounded in the project stack, scope or roadmap. Do not install every profile or the entire catalog. Existing manifests retain their selections under plan/sync/doctor. Persist new needs with project add, then sync and doctor; load only relevant instructions for each task.', '',
                'Use one authoritative process where approaches overlap and resolve declared conflicts. Profiles install guidance, not missing runtimes.', '', '| Profile | Purpose | Selected IDs |', '| --- | --- | --- |']
    for name, profile in sorted(data['profiles'].items()):
        catalog.append('| `' + name + '` | ' + cell(profile['description']) + ' | ' + cell(profile['skills']) + ' |')
    project = [e for e in entries if e['scope'] == 'project']
    for category in sorted({e['category'] for e in project}):
        catalog += ['', '## ' + category.replace('-', ' ').capitalize(), '', '| ID | Purpose | Source | Requirements / caveats |', '| --- | --- | --- | --- |']
        for e in sorted((e for e in project if e['category'] == category), key=lambda e: e['id']):
            catalog.append('| `' + e['id'] + '` | ' + cell(e['description']) + ' | ' + source_link(e, data) + ' | ' + cell(e.get('dependencies', []) + e.get('caveats', [])) + ' |')
    catalog += ['', '## Manual integrations and repair candidates', '', 'These entries are intentionally unavailable to automatic registration. See the detailed reviews and [runtime contracts](runtime-integrations.md). Useful parts can be promoted after the recorded work is completed.', '', '| ID | Purpose | Source | Remaining work |', '| --- | --- | --- | --- |']
    for e in sorted((e for e in entries if e['scope'] == 'manual'), key=lambda e: e['id']):
        catalog.append('| `' + e['id'] + '` | ' + cell(e['description']) + ' | ' + source_link(e, data) + ' | ' + cell(e.get('dependencies', []) + e.get('caveats', [])) + ' |')
    sources = ['# Source review and coverage', '', '<!-- Generated by scripts/render_registry.py; evidence lives in reviews/. -->', '',
               'Reviewed ' + data['reviewed_on'] + '. ' + count_line, '',
               'The 27 requested repositories and the official successor to OpenAI\'s deprecated skills repository are represented. Deep review covers selected bodies, applicable companions and integration boundaries. The inventory also contains mirrors, discovery stubs and candidates whose internals have not been fully read. It is not a claim that every line of every source has been audited.', '',
               '- **Installable:** reviewed selection with exact source and adapted hashes, retained notices, and recorded dependencies. This is not runtime certification.',
               '- **Manual:** valuable skill/package with specific runtime, correctness, companion or licensing work remaining.',
               '- **Indexed-only:** source discovery metadata needing review before selection. Advertisement-only wrappers remain labeled.', '',
               'No upstream installers, paid APIs or runtime programs were executed during source review. Original authored workflows provide portable alternatives where copying an upstream package would be unsuitable.', '',
               '## Pinned sources', '', '| Source | Indexed records | Project selections | License / integration boundary |', '| --- | ---: | ---: | --- |']
    for identifier, source in data['sources'].items():
        n = sum(e['source'] == identifier for e in index['skills'])
        selected = sum(e.get('source') == identifier for e in project)
        sources.append('| [' + source['repository'] + '](https://github.com/' + source['repository'] + '/tree/' + source['commit'] + ') | ' + str(n) + ' | ' + str(selected) + ' | ' + cell(source.get('license_summary', source.get('license', 'Per-entry review'))) + ' |')
    sources += ['', '## Detailed evidence', '',
                '- [Vercel browser and React skills](reviews/vercel.md): runtime boundaries, host assumptions, React companions and deployment concerns.',
                '- [Addy engineering and Remotion media](reviews/quality-media.md): shared-reference remaps, exact corrections and Remotion license uncertainty.',
                '- [Planning and search visibility](reviews/planning-search.md): hook-bearing planning packages, measurement defects and authored replacements.',
                '- [Engineering and full runtimes](reviews/expanded-engineering.md): Matt, Superpowers, Gstack, Graphify and context-mode.',
                '- [Design and visual publishing](reviews/expanded-design.md): UI UX Pro Max, Hallmark, Taste, Emil, Diagram Design, OpenDesign, Impeccable and Archify.',
                '- [Systems, marketing and productivity](reviews/expanded-marketing-systems.md): ECC, Awesome Skills, marketingskills and ADHD.',
                '- [Provider sources](reviews/providers.md): OpenAI, Google, Anthropic and Caveman.', '',
                'Earlier engineering/design/marketing reports retain historical review evidence; their minimal-selection recommendations are superseded by the current registry. Source descriptions are untrusted discovery data. Temporary checkout names in review provenance are not installation dependencies.', '',
                '## Material boundaries', '',
                'Agent-browser is a native browser runtime, not just a skill file; its install and authentication paths need explicit setup. Planning-with-files has lifecycle hooks in skill frontmatter. The authored work-planning skill supplies portable durable state without those hooks. GEO workflows contain unsupported scores and factual assumptions; search-visibility supplies evidence-based alternatives. Addy selections retain repository-level companions through explicit file maps and bounded literal corrections.', '',
                'Remotion lacks an explicit verified license at the pinned revision and remains manual. Vercel agent-skills declares MIT in README/frontmatter but supplies no standalone license file; that evidence and caveat are retained. Context-mode uses Elastic-2.0. Anthropic office implementations have restrictive local terms. Awesome Skills has per-source exceptions. OpenDesign includes advertisement-only wrappers. These boundaries are not erased by marketplace export.', '',
                '## Verification and maintenance', '',
                'See [verification evidence](verification.md) for source-byte checks, isolated registration and platform limits. Update source pins, reviewed payload hashes, integration notes and inventory together. Use `python3 ai.py catalog hash <id> --source-tree /reviewed/checkout` to calculate hashes; this does not approve new bytes. Regenerate discovery docs with `python3 scripts/render_registry.py`.', '',
                'Global links follow the checkout; managed copies and project installations change through synchronization. Local edits are preserved. Shared instructions require appropriate skill pickup but cannot guarantee model behavior or enforce a security boundary.']
    return {ROOT / 'docs/catalog.md': '\n'.join(catalog) + '\n',
            ROOT / 'docs/source-review.md': '\n'.join(sources) + '\n'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    changed = []
    for path, content in render().items():
        if not path.exists() or path.read_text() != content:
            changed.append(str(path.relative_to(ROOT)))
            if not args.check:
                path.write_text(content, encoding='utf-8')
    if changed:
        print(('Stale: ' if args.check else 'Updated: ') + ', '.join(changed))
    return 1 if args.check and changed else 0


if __name__ == '__main__':
    sys.exit(main())
